linters:
  enable:
    - errorlint
    - unconvert
    - unparam
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - gofmt
    - gosec
    - nilerr
    - usestdlibvars
    - decorder
    - dupl
    - dupword
    - durationcheck
    - errname
    - gocheckcompilerdirectives
    - gochecknoinits
    - mirror
    - misspell
    - musttag
    - predeclared
    - reassign
    - thelper
    - wastedassign
    - lll
    - errchkjson
    - prealloc
    - stylecheck
    - revive

linters-settings:
  funlen:
    lines: -1 # don't count lines, only statements
    ignore-comments: true
  nestif:
    min-complexity: 4
